baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/etienneburdet/twenty-twenty-ferber"
title = "Exceptionnal house in Paris"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/chambres"
name = "Chambres"
weight = "2"
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
