[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "Une smaison d'exception, avec jardin dans Paris"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Quatres chambres dans un cadre unique, verdoyant et fleuri. Proche de tous les moyens de transports ( Bus, Tram, Métro, Vélo, Motolyb, voiture de location à l’heure).\n\nVous trouverez le charme de Paris et le plaisir que donne la campagne."
[params.call_to_action]
button_label = "Contactez nous"
button_url = "contact"
content = "Consultez les disponibilités"
enable = true
title = "Réservez maintenant"
[params.footer]
address = "123 Main Street <br> New York, NY 10001"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
